# Generated by Django 5.1.1 on 2024-10-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fee",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
