# Generated by Django 5.1.1 on 2024-10-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_lecturer_name"),
        ("core", "0002_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="courses",
            field=models.ManyToManyField(max_length=12, to="core.course"),
        ),
    ]
