# Generated by Django 5.1.1 on 2024-10-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_lecturer_email_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
    ]
