# Generated by Django 5.1.1 on 2024-10-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_lecturer_email_alter_lecturer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Full Name'),
        ),
    ]
